# Generated by Django 5.1.4 on 2024-12-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("idxrow", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("idxrow", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("imgPath", models.CharField(max_length=255)),
                ("duration", models.PositiveIntegerField()),
                ("language", models.CharField(max_length=50)),
                ("userRating", models.CharField(max_length=10)),
                ("mpaaRating", models.JSONField()),
                ("genre", models.ManyToManyField(to="web.genre")),
            ],
        ),
    ]
