# Generated by Django 5.1.4 on 2024-12-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="mpaaRating",
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
    ]
