# Generated by Django 5.1.4 on 2024-12-31 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_remove_movie_genre_remove_movie_mpaarating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="mpaaRating_label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="mpaaRating_type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
