# Generated by Django 5.1.4 on 2024-12-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_movie_genre_movie_mpaarating_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="imgPath",
            field=models.ImageField(upload_to="movies/"),
        ),
    ]
