# Generated by Django 5.1.4 on 2024-12-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_movie_imgpath"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="imgPath",
            field=models.ImageField(upload_to="assets/images/"),
        ),
    ]
